-- Enable output for all blocks
SET SERVEROUTPUT ON;

-- Drop tables if they already exist
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOANS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(50),
  AGE NUMBER,
  BALANCE NUMBER,
  ISVIP VARCHAR2(5) DEFAULT 'FALSE'
);

-- Create LOANS table
CREATE TABLE LOANS (
  LOAN_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER,
  INTEREST_RATE NUMBER,
  DUE_DATE DATE,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Insert sample data into CUSTOMERS
INSERT INTO CUSTOMERS VALUES (1, 'John Doe', 65, 15000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (2, 'Alice Smith', 45, 8000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (3, 'Ram Kumar', 70, 12000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (4, 'Meena Verma', 28, 10500, 'FALSE');

-- Insert sample data into LOANS
INSERT INTO LOANS VALUES (101, 1, 10, SYSDATE + 10); -- due soon
INSERT INTO LOANS VALUES (102, 2, 12, SYSDATE + 40); -- due later
INSERT INTO LOANS VALUES (103, 3, 9, SYSDATE + 5);   -- due soon
INSERT INTO LOANS VALUES (104, 4, 11, SYSDATE + 25); -- due soon

COMMIT;
