-- Drop existing tables safely
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SAVINGS_ACCOUNTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Table: SAVINGS_ACCOUNTS
CREATE TABLE SAVINGS_ACCOUNTS (
  ACCOUNT_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER,
  BALANCE NUMBER
);

-- Table: EMPLOYEES
CREATE TABLE EMPLOYEES (
  EMP_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(50),
  DEPARTMENT_ID NUMBER,
  SALARY NUMBER
);

-- Table: ACCOUNTS
-- Create the ACCOUNTS table
CREATE TABLE ACCOUNTS (
  ACCOUNT_NO NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER,
  BALANCE NUMBER
);

-- Insert sample data
INSERT INTO SAVINGS_ACCOUNTS VALUES (101, 1, 10000);
INSERT INTO SAVINGS_ACCOUNTS VALUES (102, 2, 20000);

INSERT INTO EMPLOYEES VALUES (1, 'Anita', 10, 50000);
INSERT INTO EMPLOYEES VALUES (2, 'Ravi', 10, 60000);
INSERT INTO EMPLOYEES VALUES (3, 'Meera', 20, 70000);

INSERT INTO ACCOUNTS VALUES (1111, 1, 15000);
INSERT INTO ACCOUNTS VALUES (2222, 2, 10000);

COMMIT;
